using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System.IO;

/*
 * This script parses a textfile containing sensor data which was generated by an external python script.
 * The textfile is formatted "int int int int " and the data is ordered top, bottom, left, right.
 * The unit of each int in the textfile is kg on the specific side of the balance board.
 * Then the two directions of each axis are combined into one float and normalized by dividing by the total weight,
 * so the result values are floats between -1 and 1.
 */


public class BalanceBoardInput : MonoBehaviour
{
	public float x;
	public float y;

	//private const String pattern = @"(\d+)(\s+)(\d+)(\s+)(\d+)(\s+)(\d+)";

	// Use this for initialization
	void Start ()
	{
		
	}
	
	// Update is called once per frame
	void Update ()
	{
		// read data file generated by python script
		string balanceBoardDataString = System.IO.File.ReadAllText("balanceBoardData");

		try
		{
			// perform string parsing magic
			string[] subStrings = balanceBoardDataString.Split(' ');
			float[] balanceBoardData = {0, 0, 0, 0};
			float weightSum = 0;	// total weight of the player, used to normalize data

			for(int i = 0; i < 4; i++)
			{
				balanceBoardData[i] = (float)int.Parse(subStrings[i]);
				weightSum += balanceBoardData[i];
			}
			// the string is now parsed into a float[4] array

			// now combine the two directions into one axis and divide it by the total weight to get values between -1 and 1
			x = (balanceBoardData[2] - balanceBoardData[3]) / weightSum;
			y = (balanceBoardData[0] - balanceBoardData[1]) / weightSum;

			//Debug.Log(x);
		}
		catch(System.FormatException e)
		{
			// the file was not readable
		}
	}
}	